version: "3.8"

services:
  rebbitmq3:
    container_name: rabbitmq3
    image: rabbitmq:3.9.22-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
  redis:
    container_name: redis
    image: redis:alpine3.16
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6666:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  redis-client:
    container_name: redis-client
    image: redis:alpine3.16
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5555:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres: